// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjn8P4L0u9dUyWGm0n39IZTQ9VT9rrcc',
    appId: '1:309315879671:web:9cc6db7da98a5098fe09f2',
    messagingSenderId: '309315879671',
    projectId: 'prova-flora',
    authDomain: 'prova-flora.firebaseapp.com',
    storageBucket: 'prova-flora.firebasestorage.app',
    measurementId: 'G-49HMCN7Y3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-yOCcf0uDGKqSS-DVckm_uYwUtZzl4F4',
    appId: '1:309315879671:android:da99d85ea6824c85fe09f2',
    messagingSenderId: '309315879671',
    projectId: 'prova-flora',
    storageBucket: 'prova-flora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Z1CJHQRqTHZ0OxEvnKtgVFzp-1OEIus',
    appId: '1:309315879671:ios:27d9173f191f5fa8fe09f2',
    messagingSenderId: '309315879671',
    projectId: 'prova-flora',
    storageBucket: 'prova-flora.firebasestorage.app',
    iosBundleId: 'com.example.psadassa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Z1CJHQRqTHZ0OxEvnKtgVFzp-1OEIus',
    appId: '1:309315879671:ios:27d9173f191f5fa8fe09f2',
    messagingSenderId: '309315879671',
    projectId: 'prova-flora',
    storageBucket: 'prova-flora.firebasestorage.app',
    iosBundleId: 'com.example.psadassa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQjn8P4L0u9dUyWGm0n39IZTQ9VT9rrcc',
    appId: '1:309315879671:web:67fadfceba6dbab4fe09f2',
    messagingSenderId: '309315879671',
    projectId: 'prova-flora',
    authDomain: 'prova-flora.firebaseapp.com',
    storageBucket: 'prova-flora.firebasestorage.app',
    measurementId: 'G-XDJPZZ7HCX',
  );

}